gtp shit and i give up soon

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,7 +1,4 @@
-options:
-  docker: true
-
-image: laravelsail/php83-composer:latest
+image: docker:stable
 
 pipelines:
   branches:
@@ -12,19 +9,10 @@ pipelines:
             - docker
             - composer
           script:
+            - docker info
             - echo "Copying environment file and installing dependencies"
             - cp .env.example .env
             - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php83-composer:latest composer install --ignore-platform-reqs
-            - |
-              if [ $? -ne 0 ]; then
-                echo "Composer install failed"
-                exit 1
-              fi
-            - ls
-            - cd vendor/bin
-            - ls
-            - cd ..
-            - cd ..
-            - ./vendor/bin/sail up -d
-            - ./vendor/bin/sail php artisan test
-            - ./vendor/bin/sail down
+            - docker-compose up -d
+            - ./vendor/bin/sail php artisan test || { echo "Tests failed"; exit 1; }
+            - docker-compose down
