revert and i give up

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -1,4 +1,7 @@
-image: docker:stable
+options:
+  docker: true
+
+image: laravelsail/php83-composer:latest
 
 pipelines:
   branches:
@@ -9,10 +12,14 @@ pipelines:
             - docker
             - composer
           script:
-            - docker info
             - echo "Copying environment file and installing dependencies"
             - cp .env.example .env
             - docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/var/www/html" -w /var/www/html laravelsail/php83-composer:latest composer install --ignore-platform-reqs
-            - docker-compose up -d
-            - ./vendor/bin/sail php artisan test || { echo "Tests failed"; exit 1; }
-            - docker-compose down
+            - |
+              if [ $? -ne 0 ]; then
+                echo "Composer install failed"
+                exit 1
+              fi
+            - ./vendor/bin/sail up -d
+            - ./vendor/bin/sail php artisan test
+            - ./vendor/bin/sail down
